// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions]
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyZ_BirUFF6NB45tkBOBCh0yd2xluYinA',
    appId: '1:707272338076:web:a37738325b3769e6175b59',
    messagingSenderId: '707272338076',
    projectId: 'kmwd-3e109',
    authDomain: 'kmwd-3e109.firebaseapp.com',
    storageBucket: 'kmwd-3e109.firebasestorage.app',
    measurementId: 'G-88JLG1LJD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfqxCgfI2wXEfOEdh626D7_Uh1mSkcnLw',
    appId: '1:707272338076:android:ab9957f48c2ff017175b59',
    messagingSenderId: '707272338076',
    projectId: 'kmwd-3e109',
    storageBucket: 'kmwd-3e109.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbDUolW7BDg-y0Z_lwaG4aO5ztvG3iO6k',
    appId: '1:707272338076:ios:d956bc4dbc17568b175b59',
    messagingSenderId: '707272338076',
    projectId: 'kmwd-3e109',
    storageBucket: 'kmwd-3e109.firebasestorage.app',
    iosBundleId: 'com.example.kmwd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbDUolW7BDg-y0Z_lwaG4aO5ztvG3iO6k',
    appId: '1:707272338076:ios:d956bc4dbc17568b175b59',
    messagingSenderId: '707272338076',
    projectId: 'kmwd-3e109',
    storageBucket: 'kmwd-3e109.firebasestorage.app',
    iosBundleId: 'com.example.kmwd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyZ_BirUFF6NB45tkBOBCh0yd2xluYinA',
    appId: '1:707272338076:web:947470eb63d7c723175b59',
    messagingSenderId: '707272338076',
    projectId: 'kmwd-3e109',
    authDomain: 'kmwd-3e109.firebaseapp.com',
    storageBucket: 'kmwd-3e109.firebasestorage.app',
    measurementId: 'G-SG76RW5RR5',
  );
}
